---
- name: Create sites docroots
  file:
    path: "/var/www/nginx/{{ item }}/docroot"
    state: directory
  loop: "{{ groups['containers'] }}"

- name: Create sites config
  template:
    src: templates/vhost_{{ hostvars[item].role }}.j2
    dest: "/etc/nginx/conf.d/10.{{ item }}.conf"
  loop: "{{ groups['containers'] }}"
  when: "item != inventory_hostname"

- name: Create docroot dirs
  file:
    path: "/var/www/{{ item }}/docroot"
    state: directory
  loop: "{{ groups['containers'] }}"
  when: "item != inventory_hostname"

- name: Copy certs
  command: "bash /root/copy-certs.sh"
...
