---
- hosts: saint-nectaire
  remote_user: root

  vars_prompt:
    - name: "user"
      prompt: "what is the username for the new website owner?"
      private: no
    - name: "domain"
      prompt: "what is the main domain name for the website? (if many, separate them with commas)"
      private: no

  tasks:
    - name: Create facts
      set_fact:
          domains: "{{ domain.split(',') }}"
    - name: Create facts
      set_fact:
          main_domain: "{{ domains | first }}"
    - name: Create facts
      set_fact:
          alt_domains: "{{ domains | difference(main_domain) }}"

    - name: "Create user"
      user: name="{{ user }}" shell="/bin/bash"

    - name: "Add my public key to user"
      authorized_key: user="{{ user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Create virtual host
      template: src=templates/vhost.j2 dest="/etc/nginx/sites-available/{{ user }}"

    - include: tasks/letsencrypt.yml

    - name: Activate virtual host
      file: src="/etc/nginx/sites-available/{{ user }}" dest="/etc/nginx/sites-enabled/{{ user }}" state=link
      notify: reload nginx

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
...
