---
- hosts: saint-nectaire
  remote_user: root

  vars_prompt:
    - name: "domain"
      prompt: "what is the main domain name for the website? (if many, separate them with commas)"
      private: no

  tasks:
    - include: tasks/letsencrypt.yml

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
...
