---
- hosts: containers
  vars_prompt:
    - name: "host"
      prompt: "what is the container domain to setup?"
      private: no
  tasks:

    - name: Get firewall facts
      set_fact:
        firewall_ip: "10.0.{{ hostvars[node].vlan }}.{{ hostvars[node].ctid }}"
        firewall_public_ip: "{{ hostvars[node].public_ip }}"
        firewall_gateway: "{{ hostvars[node].gateway }}"
        firewall_public_ip6: "{{ hostvars[node].public_ip6 }}"
        firewall_gateway6: "{{ hostvars[node].gateway6 }}"
        firewall_mac: "{{ hostvars[node].mac }}"
      when: hostvars[node].role == 'firewall'
      loop: "{{ groups['containers'] }}"
      loop_control:
        loop_var: node

    - name: Get reverse proxy facts
      set_fact:
        reverse_proxy_ip: "10.0.{{ hostvars[node].vlan }}.{{ hostvars[node].ctid }}"
        reverse_proxy_ctid: "{{ hostvars[node].ctid }}"
      when: hostvars[node].role == 'http'
      loop: "{{ groups['containers'] }}"
      loop_control:
        loop_var: node

    - name: Get mailinabox facts
      set_fact:
        miab_ip: "10.0.{{ hostvars[node].vlan }}.{{ hostvars[node].ctid }}"
        miab_ctid: "{{ hostvars[node].ctid }}"
        miab_domain: "{{ node }}"
      when: hostvars[node].role == 'miab'
      loop: "{{ groups['containers'] }}"
      loop_control:
        loop_var: node

    - name: Fetch role vars
      include_vars:
        file: "{{ playbook_dir }}/roles/{{ role_name }}/defaults/main.yml"
        name: "{{ role_name }}"
      loop:
        - http
        - miab
        - osp
        - mastodon
        - matrix
        - funkwhale
        - wordpress
        - static
        - isso
        - notebook
      loop_control:
        loop_var: role_name

    - name: Set roles vars fact
      set_fact:
        roles_vars:
          http: "{{ http }}"
          miab: "{{ miab }}"
          osp: "{{ osp }}"
          mastodon: "{{ mastodon }}"
          matrix: "{{ matrix }}"
          funkwhale: "{{ funkwhale }}"
          wordpress: "{{ wordpress }}"
          static: "{{ static }}"
          isso: "{{ isso }}"
          notebook: "{{ notebook }}"

    - name: Setup the containers system
      include_role:
        name: "{{ role }}"
        tasks_from: system
      when: "host == inventory_hostname"

    - name: Finish the containers setup
      include_role:
        name: "{{ role }}"
        tasks_from: post-system

...
