---
- hosts: hypervisors
  remote_user: root

  tasks:
    - name: Get reverse proxy facts
      set_fact:
        reverse_proxy_ip: "10.0.{{ hostvars[node].vlan }}.{{ hostvars[node].ctid }}"
        reverse_proxy_ctid: "{{ hostvars[node].ctid }}"
      when: hostvars[node].role == 'http'
      loop: "{{ groups['containers'] }}"
      loop_control:
        loop_var: node

    - name: Unlock container
      include: tasks/unlock_volume.yml
      loop: "{{ groups['containers'] }}"

    - name: Start nginx
      command: "pct exec {{ reverse_proxy_ctid }} /etc/init.d/nginx start"
...
