image: "alpine-3.11-default_20200425_amd64.tar.xz"
ostype: "alpine"
disk_size: "16"
cpu_cores: "2"
cpu_units: "1024"
memory: "1024"
swap: "1024"
allow_ssh: "no"
redirected_ports: []
blackbox:
  enable: yes
