---
- name: Set hostvars
  set_fact:
    host: "{{ hostvars[item] }}"
    main_domain: "{{ item }}"
    ctid: "{{ hostvars[item].ansible_ssh_extra_args }}"
    vlan: "{{ hostvars[item].vlan }}"
    passphrase: "{{ hostvars[item].zfs_volume_passphrase }}"
    backup_passphrase: "{{ hostvars[item].backup_passphrase }}"
    role: "{{ hostvars[item].role }}"
    zfs_volume: "{{ hostvars[item].pool }}"
- name: Include role
  include_role:
    name: "{{ host.role }}"
    tasks_from: container
# - name: Create public dir
#   file:
#     path: "/{{ hostvars[item] }}.pool/subvol/{{ ctid }}-disk-0/srv/public"
#     state: directory
- name: Create container symlink
  file:
    src: "/{{ hostvars[item].pool }}/subvol-{{ ctid }}-disk-0"
    dest: "/var/containers/{{ item }}"
    state: link
- name: Create role symlink
  file:
    src: "/var/containers/{{ item }}"
    dest: "/var/containers/{{ role }}"
    state: link
  when: "role in ['miab', 'http']"

...
