---
- name: Set hostvars
  set_fact:
    host: "{{ hostvars[item] }}"
    main_domain: "{{ item }}"
    ctid: "{{ hostvars[item].ansible_ssh_extra_args }}"
    vlan: "{{ hostvars[item].vlan }}"

- name: Get existing ZFS volume passphrase
  set_fact:
    passphrase: "{{ hostvars[item].passphrase | default(lookup('password', '/dev/null length=64')) }}"

- name: Create other vars
  set_fact:
    zfs_volume: "rpool/data/encrypted-{{ ctid }}"
    vlan: "{% if vlan %}{{ vlan }}{% else %}{{ ctid }}{% endif %}"

- name: Get existing backup passphrase
  set_fact:
    backup_passphrase: "{{ hostvars[item].backup_passphrase }}"
  when: hostvars[item].backup_passphrase is defined

- name: Create backup passphrase
  set_fact:
    backup_passphrase: "{{ lookup('password', '/dev/null length=64') }}"
  when: backup_passphrase is not defined

- name: Get existing backup SSH private key
  set_fact:
    backup_ssh_key: "{{ hostvars[item].backup_ssh_key }}"
  when: hostvars[item].backup_ssh_key is defined

- name: Create backup SSH private key
  set_fact:
    backup_ssh_key: "{{ lookup('file', 'tmp/' + item + '-backup') }}"
  when: backup_ssh_key is not defined

- name: Get existing backup SSH public key
  set_fact:
    backup_ssh_pub_key: "{{ hostvars[item].backup_ssh_pub_key }}"
  when: hostvars[item].backup_ssh_pub_key is defined

- name: Create backup SSH public key
  set_fact:
    backup_ssh_pub_key: "{{ lookup('file', 'tmp/' + item + '-backup.pub') }}"
  when: backup_ssh_pub_key is not defined

- name: Get mail account passphrase
  set_fact:
    mail_account_passphrase: "{{ hostvars[item].mail_account_passphrase }}"
  when: hostvars[item].mail_account_passphrase is defined

- name: Create mail account password
  set_fact:
    mail_account_passphrase: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
  when: mail_account_passphrase is not defined

- name: Call custom secrets generation
  include_role:
    name: "{{ hostvars[item].role }}"
    tasks_from: secrets

- name: Add Ansible Host
  add_host:
    name: "{{ item }}"
    domain: "{{ main_domain }}"
    ct_hostname: "{{ main_domain }}"
    ctid: "{{ ctid }}"
    zfs_volume_passphrase: "{{ passphrase }}"
    backup_passphrase: "{{ backup_passphrase }}"
    backup_ssh_key: "{{ backup_ssh_key }}"
    backup_ssh_pub_key: "{{ backup_ssh_pub_key }}"
    mail_account_passphrase: "{{ mail_account_passphrase }}"
    extra_secrets: "{{ extra_secrets }}"
    zfs_pool: "{{ zfs_volume }}"
    zfs_volumes:
      - "{{ zfs_volume }}/subvol-{{ ctid }}-disk-0"
    ip: "10.0.{{ vlan }}.{{ ctid }}"
    vlan: "{{ vlan }}"
...
