---
- name: Get Wordpress secrets
  set_fact:
    wordpress_admin_password: "{{ hostvars[item].wordpress_admin_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    database_password: "{{ hostvars[item].database_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    database_admin_password: "{{ hostvars[item].database_admin_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Set extra secrets
  set_fact:
    extra_secrets:
      wordpress_admin_password: "{{ wordpress_admin_password }}"
      database_password: "{{ database_password }}"
      database_admin_password: "{{ database_admin_password }}"
...
