---
- name: Test from R1:main
  debug:
    msg: "Hello from R1:main. test={{ test }}"
- name: Check file resolution
  copy:
    src: files/test_r2
    dest: /tmp/test_file
- name: Check file contents
  command: cat /tmp/test_file
  register: "cat"
- name: Show file contents
  debug:
    msg: "{{ cat }}"
- name: Remove file
  file:
    path: /tmp/test_file
    state: absent
...
