---
- name: update system
  apt:
    upgrade: dist
    update_cache: yes

- name: Copy timezone data
  copy:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    remote_src: yes

- name: Generate locale
  command: locale-gen en_US.UTF-8


- name: Disable firewall
  command: "ufw disable"

- name: Install opensmtpd
  apt:
    name: opensmtpd

- name: Configure SMTP relay
  template:
    src: templates/smtpd.conf
    dest: /etc/smtpd.conf

- name: Create smtpd directory
  file:
    path: /etc/smtpd
    state: directory

- name: Configure SMTP secrets
  template:
    src: templates/secrets
    dest: /etc/smtpd/secrets
    mode: "0640"

- name: Start smtpd
  service:
    name: opensmtpd
    state: started
    runlevel: default
...
