---
- name: Setup container
  include_role:
    name: container
    tasks_from: container

- name: Install iptables in container
  command: "pct exec {{ ctid }} /sbin/apk add iptables"

- name: Install ip6tables in container
  command: "pct exec {{ ctid }} /sbin/apk add ip6tables"

- name: Install vlan in container
  command: "pct exec {{ ctid }} /sbin/apk add vlan"

- name: Set forwarding
  lineinfile:
    path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/sysctl.d/01-firewall.conf"
    line: "net.ipv6.conf.all.forwarding=1"
    create: yes
  register: ipv6_forwarding

- name: Reload sysctl
  command: "sysctl -p"
  when: ipv6_forwarding.changed

- name: Create vlan interfaces
  template:
    src: templates/interfaces.j2
    dest: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/network/interfaces"
  # blockinfile:
  #   path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/network/interfaces"
  #   block: |
  #     {% for host in groups['containers'] %}
  #     {% if hostvars[host].vlan != '0' %}
  #     auto eth0.{{ hostvars[host].vlan }}
  #     iface eth0.{{ hostvars[host].vlan }} inet static
  #         address 10.0.{{ hostvars[host].vlan }}.1
  #         netmask 255.255.255.0
  #         post-up ip r a 10.0.{{ hostvars[host].vlan }}.0/24 dev eth0.{{ hostvars[host].vlan }}

  #     iface eth0.{{ hostvars[host].vlan }} inet6 static
  #         address {{ public_ip6[:17] }}{{ ctid | hex }}::2
  #         netmask 64
  #         post-up ip r a {{ public_ip6[:17] }}{{ hostvars[host].vlan | hex }}::/64 dev eth0.{{ hostvars[host].vlan }}

  #     {% endif %}
  #     {% endfor %}
  register: bridge_task

- name: Restart container networking to enable vlans
  command: "pct exec {{ ctid }} /etc/init.d/networking restart"
  when: bridge_task.changed

- name: Fetch role vars (for firewall ports)
  include_vars:
    file: "{{ playbook_dir }}/roles/{{ role_name }}/defaults/main.yml"
    name: "{{ role_name }}"
  loop:
    - http
    - miab
    - osp
    - mastodon
    - matrix
    - funkwhale
    - wordpress
    - static
    - isso
    - notebook
  loop_control:
    loop_var: role_name

- name: Set roles vars fact
  set_fact:
    roles_vars:
      http: "{{ http }}"
      miab: "{{ miab }}"
      osp: "{{ osp }}"
      mastodon: "{{ mastodon }}"
      matrix: "{{ matrix }}"
      funkwhale: "{{ funkwhale }}"
      wordpress: "{{ wordpress }}"
      static: "{{ static }}"
      isso: "{{ isso }}"
      notebook: "{{ notebook }}"

# - name: Add sysctl conf
#   copy:
#     src: files/sysctl.conf
#     dest: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/sysctl.d/01-firewall.conf"
#     remote_src: no

- name: Add iptables rules
  template:
    src: templates/firewall_rules.j2
    dest: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/iptables/rules-save"

- name: Enable iptables service
  command: "pct exec {{ ctid }} rc-update add iptables"

- name: Start iptables service
  command: "pct exec {{ ctid }} rc-service iptables start"

- name: Reload iptables service
  command: "pct exec {{ ctid }} rc-service iptables reload"

- name: Add ip6tables rules
  template:
    src: templates/firewall_rules_v6.j2
    dest: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/iptables/rules6-save"

- name: Enable ip6tables service
  command: "pct exec {{ ctid }} rc-update add ip6tables"

- name: Start ip6tables service
  command: "pct exec {{ ctid }} rc-service ip6tables start"

- name: Reload ip6tables service
  command: "pct exec {{ ctid }} rc-service ip6tables reload"
...
