---
- name: Set custom facts
  set_fact:
    image: ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz
    ostype: ubuntu
    disk_size: 8
    cpu_cores: 1
    cpu_units: 1024
    memory: 1024
    swap: 512
    firewall_file: firewall.j2
    allow_ssh: yes
    redirected_ports: []
- name: Setup container
  include_role:
    name: app_ubuntu
    tasks_from: container
...

