groups:
- name: "prometheus-exporter"
  rules:
  - alert: ContainerDown
    expr: pve_up == 0.0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Container down (instance {{ $labels.id }})"
      description: "Container is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
