---
- name: Get extra OSP facts
  set_fact:
    osp_secret_key: "{{ hostvars[item].osp_secret_key | default(lookup('password', '/dev/null length=64')) }}"
    osp_password_salt: "{{ hostvars[item].osp_password_salt | default(lookup('password', '/dev/null length=16')) }}"
    ejabberd_pass: "{{ hostvars[item].ejabberd_pass | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    database_admin_password: "{{ hostvars[item].database_admin_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    database_password: "{{ hostvars[item].database_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
- name: Set extra secrets
  set_fact:
    extra_secrets:
      osp_secret_key: "{{ osp_secret_key }}"
      osp_password_salt: "{{ osp_password_salt }}"
      ejabberd_pass: "{{ ejabberd_pass }}"
      database_admin_password: "{{ database_admin_password }}"
      database_password: "{{ database_password }}"
...
