---
- name: Install tzdata
  apk:
    name: tzdata

- name: Copy timezone data
  copy:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    remote_src: yes

- name: Install nfs
  apk:
    name: nfs-utils

- name: Set up NFS mounts
  template:
    src: templates/exports
    dest: /etc/exports

- name: Start nfs
  service:
    name: nfs
    state: started
    runlevel: default

- name: Force activation of NFS service
  command: "rc-update add nfs default"

- name: Install opensmtpd
  apk:
    name: opensmtpd

- name: Configure SMTP relay
  template:
    src: templates/smtpd.conf
    dest: /etc/smtpd/smtpd.conf

- name: Configure SMTP secrets
  template:
    src: templates/secrets
    dest: /etc/smtpd/secrets
    mode: "0640"

# - name: Convert secrets to db format
#   command: "makemap /etc/smtpd/secrets"

- name: Start smtpd
  service:
    name: smtpd
    state: started
    runlevel: default
...
