---
- name: Upgrade system
  apk:
    upgrade: yes
    update_cache: yes

- name: Install tzdata
  apk:
    name: tzdata

- name: Copy timezone data
  copy:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    remote_src: yes

- name: Install nfs
  apk:
    name: nfs-utils

- name: Set up NFS mounts
  template:
    src: templates/exports
    dest: /etc/exports

- name: Start nfs
  service:
    name: nfs
    state: started
    runlevel: default

- name: Force activation of NFS service
  command: "rc-update add nfs default"

- name: Install opensmtpd
  apk:
    name: opensmtpd

- name: Get opensmtpd version
  shell: "smtpd -h 2>&1 | head -n 1 | cut -c 20-"
  register: opensmtpd_version

- name: Configure SMTP relay
  template:
    src: templates/smtpd.conf
    dest: /etc/smtpd/smtpd.conf
  when: opensmtpd_version.stdout == '6.0.3-portable'

- name: Configure SMTP relay
  template:
    src: templates/smtpd2.conf
    dest: /etc/smtpd/smtpd.conf
  when: opensmtpd_version.stdout != '6.0.3-portable'

- name: Configure SMTP secrets
  template:
    src: templates/secrets
    dest: /etc/smtpd/secrets
    mode: "0640"

# - name: Convert secrets to db format
#   command: "makemap /etc/smtpd/secrets"

- name: Start smtpd
  service:
    name: smtpd
    state: started
    runlevel: default

# - name: Install node-exporter
#   apk:
#     name: prometheus-node-exporter
#     update_cache: yes
#     repository:
#       - http://dl-cdn.alpinelinux.org/alpine/edge/community
#       - http://dl-cdn.alpinelinux.org/alpine/v3.10/main
#       - http://dl-cdn.alpinelinux.org/alpine/v3.10/community

# - name: Create node_exporter run dir
#   file:
#     path: /var/run/prometheus
#     state: directory
#     owner: prometheus
#     group: prometheus

# - name: Make Node Exporter listen on localhost only
#   template:
#     src: templates/default_node_exporter
#     dest: /etc/default/prometheus-node-exporter
#   register: prometheus_default_conf

# - name: Start Node Exporter
#   service:
#     name: node-exporter
#     state: started

# - name: Restart Node Exporter
#   service:
#     name: node-exporter
#     state: restarted
#   when: prometheus_default_conf.changed

...
