---
- name: Create secrets
  set_fact:
    isso_password: "{{ hostvars[item].isso_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Set extra secrets
  set_fact:
    extra_secrets:
      isso_password: "{{ isso_password }}"
...
