---
- name: Get existing Mastodon secrets
  set_fact:
    db_pass: "{{ hostvars[item].db_pass | default(lookup('password', '/dev/null length=64')) }}"
    paperclip_secret: "{{ hostvars[item].paperclip_secret | default(lookup('password', '/dev/null length=64')) }}"
    secret_key_base: "{{ hostvars[item].secret_key_base | default(lookup('password', '/dev/null length=128 chars=digits,a,b,c,d,e,f')) }}"
    otp_secret: "{{ hostvars[item].otp_secret | default(lookup('password', '/dev/null length=128 chars=digits,a,b,c,d,e,f')) }}"
    vapid_private_key: "{{ hostvars[item].vapid_private_key | default(lookup('password', '/dev/null length=64')) }}"
    vapid_public_key: "{{ hostvars[item].vapid_public_key | default(lookup('password', '/dev/null length=64')) }}"
- name: Set extra secrets
  set_fact:
    extra_secrets:
      db_pass: "{{ db_pass }}"
      db_pass: "{{ db_pass }}"
      paperclip_secret: "{{ paperclip_secret }}"
      secret_key_base: "{{ secret_key_base }}"
      otp_secret: "{{ otp_secret }}"
      vapid_private_key: "{{ vapid_private_key }}"
      vapid_public_key: "{{ vapid_public_key }}"
...
