# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alerts/*.yml"
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
    scheme: http

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
{% for node in groups['containers'] %}        - https://{{ node }}
{% endfor %}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

{% for node in groups['hypervisors'] %}
  - job_name: host-{{ node }}
    static_configs:
      - targets: ['{{ reverse_proxy_hostname }}']
    metrics_path: /{{ node }}
    params:
      module: [default]
    basic_auth:
      username: prometheus
      password: {{ prometheus_exporter_auth }}
    scheme: https

  - job_name: pve-{{ node }}
    static_configs:
      - targets: ['{{ reverse_proxy_hostname }}']
    metrics_path: /{{ node }}/pve
    params:
      module: [default]
    basic_auth:
      username: prometheus
      password: {{ prometheus_exporter_auth }}
    scheme: https

{% endfor %}
{% for node in groups['containers'] %}
{% if hostvars[node].role in roles_vars  and 'metrics' in roles_vars[hostvars[node].role] %}
{% for service_name in roles_vars[hostvars[node].role].metrics %}
  - job_name: ct-{{ service_name }}-{{ node }}
    static_configs:
      - targets: ['{{ reverse_proxy_hostname }}']
    metrics_path: /{{ node }}/{{ service_name }}
    params:
      module: [default]
    basic_auth:
      username: prometheus
      password: {{ prometheus_exporter_auth }}
    scheme: https

{% endfor %}
{% endif %}
{% endfor %}
{% for node in groups['backup'] %}
  - job_name: backup-{{ node }}
    static_configs:
      - targets: ['{{ node }}']
    metrics_path: /metrics
    params:
      module: [default]
    basic_auth:
      username: prometheus
      password: {{ prometheus_exporter_auth }}
    scheme: https

{% endfor %}
