---
- name: Set custom facts
  set_fact:
    firewall_file: firewall.j2
    image: ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz
    ostype: ubuntu
    disk_size: 128
    cpu_cores: 1
    cpu_units: 1024
    memory: 2048
    swap: 1024
- name: Setup container
  include_role:
    name: container
    tasks_from: container
- name: Create public dir
  file:
    path: /srv/public
    state: directory

# - name: Bind-mount public dirs
#   mount:
#     src: "/{{ item.pool }}/subvol-{{ item.ctid }}-disk-0/srv/public"
#     path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/srv/public/{{ item.ctid }}"
#     opts: bind
#     fstype: none
#     state: mounted
#   loop: "{{ groups['containers'] }}"
#   when: "item.ctid != ctid"

- name: Create Let’s Encrypt dir
  file:
    path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/home/user-data/ssl/lets_encrypt/webroot"
    state: directory

# - name: Bind-mount Let’s Encrypt dirs
#   mount:
#     src: "/var/containers/miab/home/user-data/ssl/"
#     path: "/var/containers/http/home/user-data/ssl"
#     opts: bind
#     fstype: none
#     state: mounted
...

