---
- name: Create secrets
  set_fact:
    database_password: "{{ hostvars[item].database_password | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
    admin_token: "{{ hostvars[item].admin_token | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"


- name: Set extra secrets
  set_fact:
    extra_secrets:
      database_password: "{{ database_password }}"
      admin_token: "{{ admin_token }}"
...
